version: '3.8'

services:
  backend:
    build:
      context: ./backend  
      dockerfile: Dockerfile
    image: src/backend
    ports:
      - "8000:8000"
    container_name: backend
    networks:
      - ponderada_network

  frontend:
    build: 
      context: ./frontend 
      dockerfile: Dockerfile
    image: src/frontend
    ports:
      - "3000:3000"
    container_name: frontend
    networks:
      - ponderada_network
    environment:
      - NODE_ENV=production

networks:
  ponderada_network:
    driver: bridge

